export const SOLUTIONS: {
  reference: string
  verseText: string
  referenceURL: string
}[] = [
  {
    reference: "Matthew 28:5-6",
    referenceURL: "https://www.bible.com/bible/1/MAT.28.5-6.KJV",
    verseText: "But the angel answered and said to the women, “Do not be afraid, for I know that you seek Jesus who was crucified. He is not here; for He is risen, as He said. Come, see the place where the Lord lay.",
  },  
  {
    reference: "John 15:5",
    referenceURL: "https://www.bible.com/bible/1/JHN.15.5.KJV",
    verseText: "I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit: for without me ye can do nothing.",
  },  
  {
    reference: "Ephesians 6:11",
    referenceURL: "https://www.bible.com/bible/1/EPH.6.11.KJV",
    verseText: "Put on the whole armour of God, that ye may be able to stand against the wiles of the devil.",
  },    
  {
    reference: "Romans 8:39",
    referenceURL: "https://www.bible.com/bible/1/ROM.8.39.KJV",
    verseText: "Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord.",
  }, 
  {
    reference: "Matthew 6:20",
    referenceURL: "https://www.bible.com/bible/1/MAT.6.20.KJV",
    verseText: "But lay up for yourselves treasures in heaven, where neither moth nor rust doth corrupt, and where thieves do not break through nor steal",
  },  
  {
    reference: "Revelations 3:20",
    referenceURL: "https://www.bible.com/bible/1/REV.3.20.KJV",
    verseText: "Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in to him, and will sup with him, and he with me.",
  },  
  {
    reference: "Luke 22:44",
    referenceURL: "https://www.bible.com/bible/1/LUK.22.44.KJV",
    verseText: "And being in an agony he prayed more earnestly: and his sweat was as it were great drops of blood falling down to the ground.",
  },  
  {
    reference: "1 Peter 5:6",
    referenceURL: "https://www.bible.com/bible/1/1PE.5.6.KJV",
    verseText: "Humble yourselves therefore under the mighty hand of God, that he may exalt you in due time",
  },   
    {
    reference: "2 Corinthians 9:7",
    referenceURL: "https://www.bible.com/bible/1/2CO.9.7.KJV",
    verseText: "Each one must give as he has decided in his heart, not reluctantly or under compulsion, for God loves a cheerful giver.",
  },    
    {
    reference: "2 Timothy 3:12",
    referenceURL: "https://www.bible.com/bible/1/2ti.3.12.KJV",
    verseText: "Indeed, all who desire to live a godly life in Christ Jesus will be persecuted.",
  }, 
    {
    reference: "1 Peter 1:13",
    referenceURL: "https://www.bible.com/bible/1/1pe.1.13.KJV",
    verseText: "Therefore, preparing your minds for action, and being sober-minded, set your hope fully on the grace that will be brought to you at the revelation of Jesus Christ.",
  },  
    {
    reference: "Genesis 30:13",
    referenceURL: "https://www.bible.com/bible/1/gen.30.13.KJV",
    verseText: "And Leah said, “Happy am I! For women have called me happy.” So she called his name Asher.",
  }, 
    {
    reference: "Psalm 121:1",
    referenceURL: "https://www.bible.com/bible/1/psa.121.1.KJV",
    verseText: "I lift up my eyes to the hills. From where does my help come?",
  },   
    {
    reference: "Matthew 9:13",
    referenceURL: "https://www.bible.com/bible/1/mat.9.13.KJV",
    verseText: "Go and learn what this means: ‘I desire mercy, and not sacrifice.’ For I came not to call the righteous, but sinners.",
  },   
    {
    reference: "Daniel 6:10",
    referenceURL: "https://www.bible.com/bible/1/dan.6.10.KJV",
    verseText: "When Daniel knew that the document had been signed, he went to his house where he had windows in his upper chamber open toward Jerusalem. He got down on his knees three times a day and prayed and gave thanks before his God, as he had done previously.",
  },  {
    reference: "Psalm 59:16",
    referenceURL: "https://www.bible.com/bible/1/psa.59.16.KJV",
    verseText: "But I will sing of your strength; I will sing aloud of your steadfast love in the morning. For you have been to me a fortress and a refuge in the day of my distress.",
  },  {
    reference: "Colossians 3:1",
    referenceURL: "https://www.bible.com/bible/1/col.3.1.KJV",
    verseText: "If then you have been raised with Christ, seek the things that are above, where Christ is, seated at the right hand of God.",
  },  {
    reference: "Genesis 40:5",
    referenceURL: "https://www.bible.com/bible/1/gen.40.5.KJV",
    verseText: "And one night they both dreamed—the cupbearer and the baker of the king of Egypt, who were confined in the prison—each his own dream, and each dream with its own interpretation.",
  },  {
    reference: "John 3:16",
    referenceURL: "https://www.bible.com/bible/1/jhn.3.16.KJV",
    verseText: "For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life.",
  },  {
    reference: "Matthew 19:29",
    referenceURL: "https://www.bible.com/bible/1/mat.19.29.KJV",
    verseText: "And everyone who has left houses or brothers or sisters or father or mother or children or lands, for my name’s sake, will receive a hundredfold and will inherit eternal life.",
  },  {
    reference: "Matthew 11:28",
    referenceURL: "https://www.bible.com/bible/1/mat.11.28.KJV",
    verseText: "Come to me, all who labor and are heavy laden, and I will give you rest.",
  },  {
    reference: "Matthew 1:21",
    referenceURL: "https://www.bible.com/bible/1/mat.1.21.KJV",
    verseText: "She will bear a son, and you shall call his name Jesus, for he will save his people from their sins.",
  },  {
    reference: "Matthew 3:4",
    referenceURL: "https://www.bible.com/bible/1/mat.3.4.KJV",
    verseText: "Now John wore a garment of camel’s hair and a leather belt around his waist, and his food was locusts and wild honey.",
  },  {
    reference: "Luke 19:7",
    referenceURL: "https://www.bible.com/bible/1/luk.19.7.KJV",
    verseText: "And when they saw it, they all grumbled, “He has gone in to be the guest of a man who is a sinner.”",
  },
  {
    reference: "Matthew 9:21",
    referenceURL: "https://www.bible.com/bible/1/mat.9.21.KJV",
    verseText: "For she said to herself, If I only touch his garment, I will be made well.",
  },
  {
    reference: "1 Thessalonians 5:23",
    referenceURL: "https://www.bible.com/bible/1/1TH.5.23.KJV",
    verseText: "Now may the God of peace himself sanctify you completely, and may your whole spirit and soul and body be kept blameless at the coming of our Lord Jesus Christ.",
  },
  {
    reference: "John 9:25",
    referenceURL: "https://www.bible.com/bible/1/JHN.9.25.KJV",
    verseText: "He answered, Whether he is a sinner I do not know. One thing I do know, that though I was blind, now I see.",
  },
  {
    reference: "Matthew 5:4",
    referenceURL: "https://www.bible.com/bible/1/MAT.5.4.KJV",
    verseText: "Blessed are those who mourn, for they shall be comforted.",
  },
  {
    reference: "Exodus 15:18",
    referenceURL: "https://www.bible.com/bible/1/EXO.15.18.KJV",
    verseText: "The LORD will reign forever and ever.",
  },
  {
    reference: "John 3:14",
    referenceURL: "https://www.bible.com/bible/1/JHN.3.14.KJV",
    verseText: "And as Moses lifted up the serpent in the wilderness, so must the Son of Man be lifted up",
  },
  {
    reference: "Revelation 22:13",
    referenceURL: "https://www.bible.com/bible/1/REV.22.13.KJV",
    verseText: "I am the Alpha and the Omega, the first and the last, the beginning and the end.",
  },
  {
    reference: "Acts 3:6",
    referenceURL: "https://www.bible.com/bible/1/ACT.3.6.KJV",
    verseText: "But Peter said, I have no silver and gold, but what I do have I give to you. In the name of Jesus Christ of Nazareth, rise up and walk!",
  },
  {
    reference: "1 Peter 3:22",
    referenceURL: "https://www.bible.com/bible/1/1PE.3.22.KJV",
    verseText: "Who has gone into heaven and is at the right hand of God, with angels, authorities, and powers having been subjected to him.",
  },
  {
    reference: "Romans 12:14",
    referenceURL: "https://www.bible.com/bible/1/ROM.12.14.KJV",
    verseText: "Bless those who persecute you; bless and do not curse them.",
  },
  {
    reference: "Matthew 11:28",
    referenceURL: "https://www.bible.com/bible/1/MAT.11.28.KJV",
    verseText: "Come to me, all who labor and are heavy laden, and I will give you rest.",
  },
  {
    reference: "Exodus 19:5",
    referenceURL: "https://www.bible.com/bible/1/EXO.19.5.KJV",
    verseText: "Now therefore, if you will indeed obey my voice and keep my covenant, you shall be my treasured possession among all peoples, for all the earth is mine",
  },
  {
    reference: "Acts 2:17",
    referenceURL: "https://www.bible.com/bible/1/ACT.2.17.KJV",
    verseText: "And in the last days it shall be, God declares, that I will pour out my Spirit on all flesh, and your sons and your daughters shall prophesy, and your young men shall see visions, and your old men shall dream dreams",
  },
  {
    reference: "Matthew 18:12",
    referenceURL: "https://www.bible.com/bible/1/MAT.18.12.KJV",
    verseText: "What do you think? If a man has a hundred sheep, and one of them has gone astray, does he not leave the ninety-nine on the mountains and go in search of the one that went astray?",
  },
  {
    reference: "2 Timothy 1:7",
    referenceURL: "https://www.bible.com/bible/1/2TI.1.7.KJV",
    verseText: "For God gave us a spirit not of fear but of power and love and self-control.",
  },
  {
    reference: "Luke 21:28",
    referenceURL: "https://www.bible.com/bible/1/LUK.21.28.KJV",
    verseText: "Now when these things begin to take place, straighten up and raise your heads, because your redemption is drawing near.",
  },
  {
    reference: "Matthew 6:26",
    referenceURL: "https://www.bible.com/bible/1/MAT.6.26.KJV",
    verseText: "Look at the birds of the air: they neither sow nor reap nor gather into barns, and yet your heavenly Father feeds them. Are you not of more value than they?",
  },
  {
    reference: "Matthew 14:31",
    referenceURL: "https://www.bible.com/bible/1/MAT.14.31.KJV",
    verseText: "Jesus immediately reached out his hand and took hold of him, saying to him, O you of little faith, why did you doubt?",
  },
  {
    reference: "2 Timothy 4:7",
    referenceURL: "https://www.bible.com/bible/1/2TI.4.7.KJV",
    verseText: "I have fought the good fight, I have finished the race, I have kept the faith.",
  },
  {
    reference: "Romans 11:36",
    referenceURL: "https://www.bible.com/bible/1/rom.11.36.KJV",
    verseText: "For from him and through him and to him are all things. To him be glory forever. Amen.",
  },
  {
    reference: "Psalm 77:20",
    referenceURL: "https://www.bible.com/bible/1/psa.77.20.KJV",
    verseText: "You led your people like a flock by the hand of Moses and Aaron.",
  },
  {
    reference: "Numbers 6:24",
    referenceURL: "https://www.bible.com/bible/1/num.6.24.KJV",
    verseText: "The LORD bless you and keep you",
  }, 
  {
    reference: "Matthew 12:1",
    referenceURL: "https://www.bible.com/bible/1/mat.12.1.KJV",
    verseText: "At that time Jesus went through the grainfields on the Sabbath. His disciples were hungry, and they began to pluck heads of grain and to eat.",
  }, 
  {
    reference: "Romans 6:23",
    referenceURL: "https://www.bible.com/bible/1/rom.6.23.KJV",
    verseText: "For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord.",
  }, 
  {
    reference: "Luke 24:2",
    referenceURL: "https://www.bible.com/bible/1/luk.24.2.KJV",
    verseText: "And they found the stone rolled away from the tomb",
  }, 
  {
    reference: "Matthew 18:12",
    referenceURL: "https://www.bible.com/bible/1/mat.18.12.KJV",
    verseText: "What do you think? If a man has a hundred sheep, and one of them has gone astray, does he not leave the ninety-nine on the mountains and go in search of the one that went astray?",
  }, 
  {
    reference: "John 1:27",
    referenceURL: "https://www.bible.com/bible/1/jhn.1.27.KJV",
    verseText: "“I baptize with water, but among you stands one you do not know, even he who comes after me, the strap of whose sandal I am not worthy to untie.”",
  }, 
  {
    reference: "Psalm 91:11",
    referenceURL: "https://www.bible.com/bible/1/psa.91.11.KJV",
    verseText: "For he will command his angels concerning you to guard you in all your ways.",
  }, 
  {
    reference: "Psalm 34:18",
    referenceURL: "https://www.bible.com/bible/1/psa.34.18.KJV",
    verseText: "The LORD is near to the brokenhearted and saves the crushed in spirit.",
  }, 
  {
    reference: "Proverbs 24:10",
    referenceURL: "https://www.bible.com/bible/1/pro.24.10.KJV",
    verseText: "If you faint in the day of adversity, your strength is small.",
  }, 
  {
    reference: "Matthew 11:29",
    referenceURL: "https://www.bible.com/bible/1/mat.11.29.KJV",
    verseText: "Take my yoke upon you, and learn from me, for I am gentle and lowly in heart, and you will find rest for your souls.",
  },  
  {
    reference: "Job 1:22",
    referenceURL: "https://www.bible.com/bible/1/job.1.22.KJV",
    verseText: "In all this Job did not sin or charge God with wrong.",
  },  
  {
    reference: "Psalm 106:2",
    referenceURL: "https://www.bible.com/bible/1/psa.106.2.KJV",
    verseText: "Who can utter the mighty deeds of the LORD, or declare all his praise?",
  },  
  {
    reference: "Romans 3:23",
    referenceURL: "https://www.bible.com/bible/1/rom.3.23.KJV",
    verseText: "For all have sinned and fall short of the glory of God.",
  },  
  {
    reference: "Isaiah 40:31",
    referenceURL: "https://www.bible.com/bible/1/isa.40.31.KJV",
    verseText: "But they who wait for the LORD shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint.",
  },  
  {  
    reference: "1 Kings 3:11-12",
    referenceURL: "https://www.bible.com/bible/1/1KI.3.11-12.KJV",
    verseText: "And God said unto him, Because thou hast asked this thing, and hast not asked for thyself long life; neither hast asked riches for thyself, nor hast asked the life of thine enemies; but hast asked for thyself understanding to discern judgment; behold, I have done according to thy words: lo, I have given thee a wise and an understanding heart; so that there was none like thee before thee, neither after thee shall any arise like unto thee."
  },
  {  
    reference: "Proverbs 29:11",
    referenceURL: "https://www.bible.com/bible/1/PRO.29.11.KJV",
    verseText: "A fool gives full vent to his spirit, but a wise man quietly holds it back.",
  },
  {  
    reference: "Mark 8:36",
    referenceURL: "https://www.bible.com/bible/1/MRK.8.36.KJV",
    verseText: "For what does it profit a man to gain the whole world and forfeit his soul?",
  },
  {  
    reference: "Proverbs 26:4-5",
    referenceURL: "https://www.bible.com/bible/1/PRO.26.4-5.KJV",
    verseText: "Answer not a fool according to his folly, lest you be like him yourself. Answer a fool according to his folly, lest he be wise in his own eyes.",
  },
  { 
    reference: "Hebrews 12:1",
    referenceURL: "https://www.bible.com/bible/1/HEB.12.1.KJV",
    verseText: "Therefore, since we are surrounded by so great a cloud of witnesses, let us also lay aside every weight, and sin which clings so closely, and let us run with endurance the race that is set before us,",
  },
  {  
    reference: "Matthew 11:29",
    referenceURL: "https://www.bible.com/bible/1/MAT.11.29.KJV",
    verseText: "Take my yoke upon you, and learn from me, for I am gentle and lowly in heart, and you will find rest for your souls.",
  },
  {  
    reference: "Genesis 1:1",
    referenceURL: "https://www.bible.com/bible/1/GEN.1.1.KJV",
    verseText: "In the beginning, God created the heavens and the earth.",
  },
  {  
    reference: "Isaiah 46:4",
    referenceURL: "https://www.bible.com/bible/1/ISA.46.4.KJV",
    verseText: "even to your old age I am he, and to gray hairs I will carry you. I have made, and I will bear; I will carry and will save.",
  },
  {  
    reference: "Genesis 28:5",
    referenceURL: "https://www.bible.com/bible/1/GEN.28.5.KJV",
    verseText: "Thus Isaac sent Jacob away. And he went to Paddan-aram, to Laban, the son of Bethuel the Aramean, the brother of Rebekah, Jacob’s and Esau’s mother.",
  },
  {  
    reference: "Psalm 64:7",
    referenceURL: "https://www.bible.com/bible/1/PSA.64.7.KJV",
    verseText: "But God shoots his arrow at them; they are wounded suddenly.",
  },
  {  
    reference: "Psalm 106:2",
    referenceURL: "https://www.bible.com/bible/1/PSA.106.2.KJV",
    verseText: "Who can utter the mighty deeds of the LORD, or declare all his praise?",
  },
  {  
    reference: "Isaiah 53:4",
    referenceURL: "https://www.bible.com/bible/1/ISA.53.4.KJV",
    verseText: "Surely he has borne our griefs and carried our sorrows; yet we esteemed him stricken, smitten by God, and afflicted.",
  },
  {  
    reference: "Matthew 6:19-20",
    referenceURL: "https://www.bible.com/bible/1/MAT.6.19-20.KJV",
    verseText: "“Do not lay up for yourselves treasures on earth, where moth and rust destroy and where thieves break in and steal, but lay up for yourselves treasures in heaven, where neither moth nor rust destroys and where thieves do not break in and steal.",
  },
  {  
    reference: "Psalm 86:11",
    referenceURL: "https://www.bible.com/bible/1/PSA.86.11.KJV",
    verseText: "Teach me your way, O LORD, that I may walk in your truth; unite my heart to fear your name.",
  },
  {  
    reference: "John 7:24",
    referenceURL: "https://www.bible.com/bible/1/JHN.7.24.KJV",
    verseText: "Do not judge by appearances, but judge with right judgment.”",
  },
  {  
    reference: "Psalm 19:14",
    referenceURL: "https://www.bible.com/bible/1/PSA.19.14.KJV",
    verseText: "Let the words of my mouth, and the meditation of my heart, be acceptable in thy sight, O LORD, my strength, and my redeemer."
  },
  {       reference: "Psalm 23:2",
    referenceURL: "https://www.bible.com/bible/1/PSA.23.2.KJV",
    verseText: "He makes me lie down in green pastures. He leads me beside still waters.",
  },
  {       reference: "John 4:14",
    referenceURL: "https://www.bible.com/bible/1/JHN.4.14.KJV",
    verseText: "but whoever drinks of the water that I will give him will never be thirsty again. The water that I will give him will become in him a spring of water welling up to eternal life.”",
  },
  {       reference: "Proverbs 23:12",
    referenceURL: "https://www.bible.com/bible/1/PRO.23.12.KJV",
    verseText: "Apply thine heart unto instruction, And thine ears to the words of knowledge."
  },
  {       reference: "John 19:39",
    referenceURL: "https://www.bible.com/bible/1/JHN.19.39.KJV",
    verseText: "Nicodemus also, who earlier had come to Jesus by night, came bringing a mixture of myrrh and aloes, about seventy-five pounds in weight.",
  },
  {       reference: "Genesis 1:27",
    referenceURL: "https://www.bible.com/bible/1/GEN.1.27.KJV",
    verseText: "So God created man in his own image, in the image of God he created him; male and female he created them.",
  },
  {       reference: "Genesis 2:18",
    referenceURL: "https://www.bible.com/bible/1/GEN.2.18.KJV",
    verseText: "Then the LORD God said, “It is not good that the man should be alone; I will make him a helper fit for him.”",
  },
  {       reference: "Psalm 146:9",
    referenceURL: "https://www.bible.com/bible/1/PSA.146.9.KJV",
    verseText: "The LORD watches over the sojourners; he upholds the widow and the fatherless, but the way of the wicked he brings to ruin.",
  },
  {       reference: "Revelation 5:5",
    referenceURL: "https://www.bible.com/bible/1/REV.5.5.KJV",
    verseText: "And one of the elders said to me, “Weep no more; behold, the Lion of the tribe of Judah, the Root of David, has conquered, so that he can open the scroll and its seven seals.”",
  },
  {       reference: "Mark 10:25",
    referenceURL: "https://www.bible.com/bible/1/MRK.10.25.KJV",
    verseText: "It is easier for a camel to go through the eye of a needle than for a rich person to enter the kingdom of God.”",
  },
  {   
    reference: "Matthew 16:18",
    referenceURL: "https://www.bible.com/bible/1/MAT.16.18.KJV",
    verseText: "And I tell you, you are Peter, and on this rock I will build my church, and the gates of hell shall not prevail against it.",
  },
  {   
    reference: "1 Kings 17:4",
    referenceURL: "https://www.bible.com/bible/1/1KI.17.4.KJV",
    verseText: "You shall drink from the brook, and I have commanded the ravens to feed you there.”",
  },
  {   
    reference: "Genesis 22:6",
    referenceURL: "https://www.bible.com/bible/1/GEN.22.6.KJV",
    verseText: "And Abraham took the wood of the burnt offering and laid it on Isaac his son. And he took in his hand the fire and the knife. So they went both of them together.",
  },
  {   
    reference: "Proverbs 22:15",
    referenceURL: "https://www.bible.com/bible/1/PRO.22.15.KJV",
    verseText: "Folly is bound up in the heart of a child, but the rod of discipline drives it far from him.",
  },
  {   
    reference: "Ecclesiastes 10:1",
    referenceURL: "https://www.bible.com/bible/1/ECC.10.1.KJV",
    verseText: "Dead flies make the perfumer’s ointment give off a stench; so a little folly outweighs wisdom and honor.",
  },
  {   
    reference: "1 Peter 5:6",
    referenceURL: "https://www.bible.com/bible/1/1PE.5.6.KJV",
    verseText: "Humble yourselves, therefore, under the mighty hand of God so that at the proper time he may exalt you,",
  },
  {   
    reference: "Luke 4:38-39",
    referenceURL: "https://www.bible.com/bible/1/LUK.4.38-39.KJV",
    verseText: "And he arose and left the synagogue and entered Simon’s house. Now Simon’s mother-in-law was ill with a high fever, and they appealed to him on her behalf. And he stood over her and rebuked the fever, and it left her, and immediately she rose and began to serve them.",
  },
  {   
    reference: "Matthew 10:30",
    referenceURL: "https://www.bible.com/bible/1/MAT.10.30.KJV",
    verseText: "But even the hairs of your head are all numbered.",
  },
  {   
    reference: "2 Corinthians 4:16",
    referenceURL: "https://www.bible.com/bible/1/2Co.4.16.KJV",
    verseText: "So we do not lose heart. Though our outer self is wasting away, our inner self is being renewed day by day.",
  },
  {   
    reference: "1 Timothy 2:1-2",
    referenceURL: "https://www.bible.com/bible/1/1TI.2.1-2.KJV",
    verseText: "First of all, then, I urge that supplications, prayers, intercessions, and thanksgivings be made for all people, for kings and all who are in high positions, that we may lead a peaceful and quiet life, godly and dignified in every way.",
  },
  {   
    reference: "Revelation 21:2",
    referenceURL: "https://www.bible.com/bible/1/REV.21.2.KJV",
    verseText: "And I saw the holy city, new Jerusalem, coming down out of heaven from God, prepared as a bride adorned for her husband.",
  },
  {   
    reference: "Exodus 16:14",
    referenceURL: "https://www.bible.com/bible/1/EXO.16.14.KJV",
    verseText: "And when the dew had gone up, there was on the face of the wilderness a fine, flake-like thing, fine as frost on the ground.",
  },
  {   
    reference: "Proverbs 15:3",
    referenceURL: "https://www.bible.com/bible/1/PRO.15.3.KJV",
    verseText: "The eyes of the LORD are in every place, keeping watch on the evil and the good.",
  },
  {   
    reference: "Acts 19:34",
    referenceURL: "https://www.bible.com/bible/1/ACT.19.34.KJV",
    verseText: "But when they recognized that he was a Jew, for about two hours they all cried out with one voice, “Great is Artemis of the Ephesians!”",
  },
  {   
    reference: "Psalm 40:17",
    referenceURL: "https://www.bible.com/bible/1/PSA.40.17.KJV",
    verseText: "As for me, I am poor and needy, but the Lord takes thought for me. You are my help and my deliverer; do not delay, O my God!",
  },
  {    reference: "Luke 3:17",
    referenceURL: "https://www.bible.com/bible/1/LUK.3.17.KJV",
    verseText: "His winnowing fork is in his hand, to clear his threshing floor and to gather the wheat into his barn, but the chaff he will burn with unquenchable fire.”",
  },
  {    reference: "Luke 22:42",
    referenceURL: "https://www.bible.com/bible/1/LUK.22.42.KJV",
    verseText: "saying, “Father, if you are willing, remove this cup from me. Nevertheless, not my will, but yours, be done.”",
  },
  {    reference: "Genesis 2:23",
    referenceURL: "https://www.bible.com/bible/1/GEN.2.23.KJV",
    verseText: "Then the man said, “This at last is bone of my bones and flesh of my flesh; she shall be called Woman, because she was taken out of Man.”",
  },
  {    reference: "Matthew 5:36",
    referenceURL: "https://www.bible.com/bible/1/MAT.5.36.KJV",
    verseText: "And do not take an oath by your head, for you cannot make one hair white or black.",
  },
  {    reference: "Luke 22:48",
    referenceURL: "https://www.bible.com/bible/1/LUK.22.48.KJV",
    verseText: "but Jesus said to him, “Judas, would you betray the Son of Man with a kiss?”",
  },
  {    reference: "Revelation 1:13",
    referenceURL: "https://www.bible.com/bible/1/REV.1.13.KJV",
    verseText: "and in the midst of the lampstands one like a son of man, clothed with a long robe and with a golden sash around his chest.",
  },
  {    reference: "Proverbs 15:1",
    referenceURL: "https://www.bible.com/bible/1/PRO.15.1.KJV",
    verseText: "A soft answer turneth away wrath: But grievous words stir up anger."
  },
  {      reference: "Titus 3:9",
    referenceURL: "https://www.bible.com/bible/1/TIT.3.9.KJV",
    verseText: "But avoid foolish controversies, genealogies, dissensions, and quarrels about the law, for they are unprofitable and worthless.",
  },
  {   reference: "Deuteronomy 10:17",
    referenceURL: "https://www.bible.com/bible/1/DEU.10.17.KJV",
    verseText: "For the LORD your God is God of gods and Lord of lords, the great, the mighty, and the awesome God, who is not partial and takes no bribe.",
  },
  {   reference: "Colossians 2:8",
    referenceURL: "https://www.bible.com/bible/1/COL.2.8.KJV",
    verseText: "See to it that no one takes you captive by philosophy and empty deceit, according to human tradition, according to the elemental spirits of the world, and not according to Christ.",
  },
  {   reference: "Galatians 6:9",
    referenceURL: "https://www.bible.com/bible/1/GAL.6.9.KJV",
    verseText: "And let us not grow weary of doing good, for in due season we will reap, if we do not give up.",
  },
  {   reference: "2 Corinthians 9:7",
    referenceURL: "https://www.bible.com/bible/1/2CO.9.7.KJV",
    verseText: "Each one must give as he has decided in his heart, not reluctantly or under compulsion, for God loves a cheerful giver.",
  },
  {   reference: "1 Timothy 5:8",
    referenceURL: "https://www.bible.com/bible/1/1TI.5.8.KJV",
    verseText: "But if anyone does not provide for his relatives, and especially for members of his household, he has denied the faith and is worse than an unbeliever.",
  },
  {   reference: "Psalm 73:24",
    referenceURL: "https://www.bible.com/bible/1/PSA.73.24.KJV",
    verseText: "You guide me with your counsel, and afterward you will receive me to glory.",
  },
  {   reference: "1 Corinthians 14:12",
    referenceURL: "https://www.bible.com/bible/1/1CO.14.12.KJV",
    verseText: "So with yourselves, since you are eager for manifestations of the Spirit, strive to excel in building up the church.",
  },
  {   reference: "Acts 13:22",
    referenceURL: "https://www.bible.com/bible/1/ACT.13.22.KJV",
    verseText: "And when he had removed him, he raised up David to be their king, of whom he testified and said, ‘I have found in David the son of Jesse a man after my heart, who will do all my will.’",
  },
  {  
    reference: "Genesis 40:5",
    referenceURL: "https://www.bible.com/bible/1/GEN.40.5.KJV",
    verseText: "And one night they both dreamed—the cupbearer and the baker of the king of Egypt, who were confined in the prison—each his own dream, and each dream with its own interpretation.",
  },
  {   reference: "2 Timothy 3:12",
    referenceURL: "https://www.bible.com/bible/1/2TI.3.12.KJV",
    verseText: "Indeed, all who desire to live a godly life in Christ Jesus will be persecuted,",
  },
  {   reference: "Psalm 119:96",
    referenceURL: "https://www.bible.com/bible/1/PSA.119.96.KJV",
    verseText: "I have seen a limit to all perfection, but your commandment is exceedingly broad.",
  },
  {   reference: "Psalm 95:6",
    referenceURL: "https://www.bible.com/bible/1/PSA.95.6.KJV",
    verseText: "Oh come, let us worship and bow down; let us kneel before the LORD, our Maker!",
  },
  {   reference: "Luke 22:31-32",
    referenceURL: "https://www.bible.com/bible/1/LUK.22.31-32.KJV",
    verseText: "“Simon, Simon, behold, Satan demanded to have you, that he might sift you like wheat, but I have prayed for you that your faith may not fail. And when you have turned again, strengthen your brothers.”",
  },
  {   reference: "Psalm 127:2",
    referenceURL: "https://www.bible.com/bible/1/PSA.127.2.KJV",
    verseText: "It is in vain that you rise up early and go late to rest, eating the bread of anxious toil; for he gives to his beloved sleep.",
  },
  {   reference: "Habakkuk 3:17-18",
    referenceURL: "https://www.bible.com/bible/1/HAB.3.17-18.KJV",
    verseText: "Though the fig tree should not blossom, nor fruit be on the vines, the produce of the olive fail and the fields yield no food, the flock be cut off from the fold and there be no herd in the stalls, yet I will rejoice in the LORD; I will take joy in the God of my salvation.",
  },
  {   reference: "Revelation 20:12",
    referenceURL: "https://www.bible.com/bible/1/REV.20.12.KJV",
    verseText: "And I saw the dead, great and small, standing before the throne, and books were opened. Then another book was opened, which is the book of life. And the dead were judged by what was written in the books, according to what they had done.",
  },
  {   reference: "Luke 2:16",
    referenceURL: "https://www.bible.com/bible/1/LUK.2.16.KJV",
    verseText: "And they went with haste and found Mary and Joseph, and the baby lying in a manger.",
  },
  {   reference: "Nahum 1:5",
    referenceURL: "https://www.bible.com/bible/1/NAM.1.5.KJV",
    verseText: "The mountains quake before him; the hills melt; the earth heaves before him, the world and all who dwell in it.",
  },
  {  
    reference: "1 Peter 1:13",
    referenceURL: "https://www.bible.com/bible/1/1PE.1.13.KJV",
    verseText: "Therefore, preparing your minds for action, and being sober-minded, set your hope fully on the grace that will be brought to you at the revelation of Jesus Christ.",
  },
  {   reference: "Joel 2:1",
    referenceURL: "https://www.bible.com/bible/1/JOL.2.1.KJV",
    verseText: "Blow a trumpet in Zion; sound an alarm on my holy mountain! Let all the inhabitants of the land tremble, for the day of the LORD is coming; it is near,",
  },
  {   reference: "Luke 12:18",
    referenceURL: "https://www.bible.com/bible/1/LUK.12.18.KJV",
    verseText: "And he said, ‘I will do this: I will tear down my barns and build larger ones, and there I will store all my grain and my goods.",
  },
  {   reference: "Exodus 20:16",
    referenceURL: "https://www.bible.com/bible/1/EXO.20.16.KJV",
    verseText: "“You shall not bear false witness against your neighbor.",
  },
  {   reference: "Psalm 104:20",
    referenceURL: "https://www.bible.com/bible/1/PSA.104.20.KJV",
    verseText: "You make darkness, and it is night, when all the beasts of the forest creep about.",
  },
  {   reference: "Ephesians 1:7",
    referenceURL: "https://www.bible.com/bible/1/EPH.1.7.KJV",
    verseText: "In him we have redemption through his blood, the forgiveness of our trespasses, according to the riches of his grace,",
  },
  {   reference: "Revelation 20:1",
    referenceURL: "https://www.bible.com/bible/1/REV.20.1.KJV",
    verseText: "Then I saw an angel coming down from heaven, holding in his hand the key to the bottomless pit and a great chain.",
  },
  {   reference: "Genesis 25:25",
    referenceURL: "https://www.bible.com/bible/1/GEN.25.25.KJV",
    verseText: "The first came out red, all his body like a hairy cloak, so they called his name Esau.",
  },
  {   reference: "Matthew 25:32",
    referenceURL: "https://www.bible.com/bible/1/MAT.25.32.KJV",
    verseText: "Before him will be gathered all the nations, and he will separate people one from another as a shepherd separates the sheep from the goats.",
  },
  {   reference: "Ephesians 3:16",
    referenceURL: "https://www.bible.com/bible/1/EPH.3.16.KJV",
    verseText: "that according to the riches of his glory he may grant you to be strengthened with power through his Spirit in your inner being,",
  },
  {  
    reference: "Romans 11:4",
    referenceURL: "https://www.bible.com/bible/1/ROM.11.4.KJV",
    verseText: "But what is God’s reply to him? “I have kept for myself seven thousand men who have not bowed the knee to Baal.”",
  },
  {       reference: "Matthew 11:28",
    referenceURL: "https://www.bible.com/bible/1/MAT.11.28.KJV",
    verseText: "Come to me, all who labor and are heavy laden, and I will give you rest.",
  },
  {    reference: "1 Corinthians 4:3",
    referenceURL: "https://www.bible.com/bible/1/1Co.4.3.KJV",
    verseText: "But with me it is a very small thing that I should be judged by you or by any human court. In fact, I do not even judge myself.",
  },
  {    reference: "Genesis 41:49",
    referenceURL: "https://www.bible.com/bible/1/GEN.41.49.KJV",
    verseText: "And Joseph stored up grain in great abundance, like the sand of the sea, until he ceased to measure it, for it could not be measured.",
  },
  {    reference: "John 15:15",
    referenceURL: "https://www.bible.com/bible/1/JHN.15.15.KJV",
    verseText: "No longer do I call you servants, for the servant does not know what his master is doing; but I have called you friends, for all that I have heard from my Father I have made known to you.",
  },
  {    reference: "Luke 9:23",
    referenceURL: "https://www.bible.com/bible/1/LUK.9.23.KJV",
    verseText: "And he said to all, “If anyone would come after me, let him deny himself and take up his cross daily and follow me.",
  },
  {    reference: "Romans 8:33",
    referenceURL: "https://www.bible.com/bible/1/ROM.8.33.KJV",
    verseText: "Who shall bring any charge against God’s elect? It is God who justifies.",
  },
  {    reference: "Exodus 9:11",
    referenceURL: "https://www.bible.com/bible/1/EXO.9.11.KJV",
    verseText: "And the magicians could not stand before Moses because of the boils, for the boils came upon the magicians and upon all the Egyptians.",
  },
  {    reference: "Ephesians 2:8-9",
    referenceURL: "https://www.bible.com/bible/1/EPH.2.8-9.KJV",
    verseText: "For by grace you have been saved through faith. And this is not your own doing; it is the gift of God, not a result of works, so that no one may boast.",
  },
  {    reference: "Psalm 127:1",
    referenceURL: "https://www.bible.com/bible/1/PSA.127.1.KJV",
    verseText: "Unless the LORD builds the house, those who build it labor in vain. Unless the LORD watches over the city, the watchman stays awake in vain.",
  },
  {   
    reference: "1 Corinthians 15:10",
    referenceURL: "https://www.bible.com/bible/1/1CO.15.10.KJV",
    verseText: "But by the grace of God I am what I am, and his grace toward me was not in vain. On the contrary, I worked harder than any of them, though it was not I, but the grace of God that is with me.",
  },
  {    reference: "John 3:36",
    referenceURL: "https://www.bible.com/bible/1/JHN.3.36.KJV",
    verseText: "Whoever believes in the Son has eternal life; whoever does not obey the Son shall not see life, but the wrath of God remains on him.",
  },
  {    reference: "Ephesians 5:18",
    referenceURL: "https://www.bible.com/bible/1/EPH.5.18.KJV",
    verseText: "And do not get drunk with wine, for that is debauchery, but be filled with the Spirit,",
  },
  {    reference: "Matthew 14:26",
    referenceURL: "https://www.bible.com/bible/1/MAT.14.26.KJV",
    verseText: "But when the disciples saw him walking on the sea, they were terrified, and said, “It is a ghost!” and they cried out in fear.",
  },
  {    reference: "James 1:22",
    referenceURL: "https://www.bible.com/bible/1/JAS.1.22.KJV",
    verseText: "But be ye doers of the word, and not hearers only, deceiving your own selves."
  },
  {    reference: "Acts 12:23",
    referenceURL: "https://www.bible.com/bible/1/ACT.12.23.KJV",
    verseText: "Immediately an angel of the Lord struck him down, because he did not give God the glory, and he was eaten by worms and breathed his last.",
  },
  {    reference: "Matthew 16:26",
    referenceURL: "https://www.bible.com/bible/1/MAT.16.26.KJV",
    verseText: "For what will it profit a man if he gains the whole world and forfeits his soul? Or what shall a man give in return for his soul?",
  },
  {    reference: "Luke 2:10",
    referenceURL: "https://www.bible.com/bible/1/LUK.2.10.KJV",
    verseText: "And the angel said to them, “Fear not, for behold, I bring you good news of great joy that will be for all the people.",
  },
  {    reference: "1 Timothy 6:17",
    referenceURL: "https://www.bible.com/bible/1/1TI.6.17.KJV",
    verseText: "As for the rich in this present age, charge them not to be haughty, nor to set their hopes on the uncertainty of riches, but on God, who richly provides us with everything to enjoy.",
  },
  {    reference: "Hebrews 11:30",
    referenceURL: "https://www.bible.com/bible/1/HEB.11.30.KJV",
    verseText: "By faith the walls of Jericho fell down after they had been encircled for seven days.",
  },
  {   
    reference: "1 John 4:7",
    referenceURL: "https://www.bible.com/bible/1/1JN.4.7.KJV",
    verseText: "Beloved, let us love one another, for love is from God, and whoever loves has been born of God and knows God.",
  },
  {    reference: "Jonah 3:6",
    referenceURL: "https://www.bible.com/bible/1/JON.3.6.KJV",
    verseText: "For word came unto the king of Nineveh, and he arose from his throne, and he laid his robe from him, and covered him with sackcloth, and sat in ashes."
  },
  {   
    reference: "Genesis 5:24",
    referenceURL: "https://www.bible.com/bible/1/GEN.5.24.KJV",
    verseText: "Enoch walked with God, and he was not, for God took him.",
  },
  { 
    reference: "Genesis 8:22",
    referenceURL: "https://www.bible.com/bible/1/GEN.8.22.KJV",
    verseText: "While the earth remains, seedtime and harvest, cold and heat, summer and winter, day and night, shall not cease.”",
  },
  { 
    reference: "Psalm 13:6",
    referenceURL: "https://www.bible.com/bible/1/PSA.13.6.KJV",
    verseText: "I will sing to the LORD, because he has dealt bountifully with me.",
  },
  { 
    reference: "Luke 9:58",
    referenceURL: "https://www.bible.com/bible/1/LUK.9.58.KJV",
    verseText: "And Jesus said to him, “Foxes have holes, and birds of the air have nests, but the Son of Man has nowhere to lay his head.”",
  },
  { 
    reference: "Deuteronomy 32:39",
    referenceURL: "https://www.bible.com/bible/1/DEU.32.39.KJV",
    verseText: "“‘See now that I, even I, am he, and there is no god beside me; I kill and I make alive; I wound and I heal; and there is none that can deliver out of my hand.",
  },
  { 
    reference: "Genesis 11:9",
    referenceURL: "https://www.bible.com/bible/1/GEN.11.9.KJV",
    verseText: "Therefore its name was called Babel, because there the LORD confused the language of all the earth. And from there the LORD dispersed them over the face of all the earth.",
  },
  { 
    reference: "Romans 15:12",
    referenceURL: "https://www.bible.com/bible/1/ROM.15.12.KJV",
    verseText: "And again Isaiah says, “The root of Jesse will come, even he who arises to rule the Gentiles; in him will the Gentiles hope.”",
  },
  { 
    reference: "Jonah 2:10",
    referenceURL: "https://www.bible.com/bible/1/JON.2.10.KJV",
    verseText: "And the LORD spoke to the fish, and it vomited Jonah out upon the dry land.",
  },
  { 
    reference: "Revelation 14:2",
    referenceURL: "https://www.bible.com/bible/1/REV.14.2.KJV",
    verseText: "And I heard a voice from heaven like the roar of many waters and like the sound of loud thunder. The voice I heard was like the sound of harpists playing on their harps,",
  },
  { 
    reference: "1 Kings 10:18",
    referenceURL: "https://www.bible.com/bible/1/1KI.10.18.KJV",
    verseText: "The king also made a great ivory throne and overlaid it with the finest gold.",
  },
  { 
    reference: "Philippians 4:7",
    referenceURL: "https://www.bible.com/bible/1/PHP.4.7.KJV",
    verseText: "And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.",
  },
  { 
    reference: "Luke 19:7",
    referenceURL: "https://www.bible.com/bible/1/LUK.19.7.KJV",
    verseText: "And when they saw it, they all grumbled, “He has gone in to be the guest of a man who is a sinner.”",
  },
  { 
    reference: "Romans 12:2",
    referenceURL: "https://www.bible.com/bible/1/ROM.12.2.KJV",
    verseText: "Do not be conformed to this world, but be transformed by the renewal of your mind, that by testing you may discern what is the will of God, what is good and acceptable and perfect.",
  },
  { 
    reference: "John 1:41",
    referenceURL: "https://www.bible.com/bible/1/JHN.1.41.KJV",
    verseText: "He first found his own brother Simon and said to him, “We have found the Messiah” (which means Christ).",
  },
  { 
    reference: "Judges 3:22",
    referenceURL: "https://www.bible.com/bible/1/JDG.3.22.KJV",
    verseText: "and the haft also went in after the blade; and the fat closed upon the blade, so that he could not draw the dagger out of his belly; and the dirt came out."
  },
  { 
    reference: "1 John 5:21",
    referenceURL: "https://www.bible.com/bible/1/1JO.5.21.KJV",
    verseText: "Little children, keep yourselves from idols.",
  },
  { 
    reference: "Mark 14:56",
    referenceURL: "https://www.bible.com/bible/1/MRK.14.56.KJV",
    verseText: "For many bore false witness against him, but their testimony did not agree.",
  },
  { 
    reference: "Psalm 100:4",
    referenceURL: "https://www.bible.com/bible/1/PSA.100.4.KJV",
    verseText: "Enter his gates with thanksgiving, and his courts with praise! Give thanks to him; bless his name!",
  },
  { 
    reference: "Luke 16:26",
    referenceURL: "https://www.bible.com/bible/1/LUK.16.26.KJV",
    verseText: "And besides all this, between us and you a great chasm has been fixed, in order that those who would pass from here to you may not be able, and none may cross from there to us.’",
  },
  { 
    reference: "Psalm 69:8",
    referenceURL: "https://www.bible.com/bible/1/PSA.69.8.KJV",
    verseText: "I have become a stranger to my brothers, an alien to my mother’s sons.",
  },
  { 
    reference: "Daniel 3:26",
    referenceURL: "https://www.bible.com/bible/1/DAN.3.26.KJV",
    verseText: "Then Nebuchadnezzar came near to the door of the burning fiery furnace; he declared, “Shadrach, Meshach, and Abednego, servants of the Most High God, come out, and come here!” Then Shadrach, Meshach, and Abednego came out from the fire.",
  },
  { 
    reference: "1 Corinthians 15:55",
    referenceURL: "https://www.bible.com/bible/1/1CO.15.55.KJV",
    verseText: "O death, where is your victory? O death, where is your sting?",
  },
  { 
    reference: "Esther 7:6",
    referenceURL: "https://www.bible.com/bible/1/EST.7.6.KJV",
    verseText: "And Esther said, “A foe and enemy! This wicked Haman!” Then Haman was terrified before the king and the queen.",
  },
  { 
    reference: "Proverbs 29:20",
    referenceURL: "https://www.bible.com/bible/1/PRO.29.20.KJV",
    verseText: "Seest thou a man that is hasty in his words? There is more hope of a fool than of him."
  },
  { 
    reference: "Psalm 118:22-23",
    referenceURL: "https://www.bible.com/bible/1/PSA.118.22-23.KJV",
    verseText: "The stone that the builders rejected has become the cornerstone. This is the LORD’s doing; it is marvelous in our eyes.",
  },
  { 
    reference: "Isaiah 2:19",
    referenceURL: "https://www.bible.com/bible/1/ISA.2.19.KJV",
    verseText: "And people shall enter the caves of the rocks and the holes of the ground, from before the terror of the LORD, and from the splendor of his majesty, when he rises to terrify the earth.",
  },
  { 
    reference: "Genesis 37:9",
    referenceURL: "https://www.bible.com/bible/1/GEN.37.9.KJV",
    verseText: "Then he dreamed another dream and told it to his brothers and said, “Behold, I have dreamed another dream. Behold, the sun, the moon, and eleven stars were bowing down to me.”",
  },
  { 
    reference: "Exodus 1:8",
    referenceURL: "https://www.bible.com/bible/1/EXO.1.8.KJV",
    verseText: "Now there arose a new king over Egypt, who did not know Joseph.",
  },
  { 
    reference: "Matthew 9:13",
    referenceURL: "https://www.bible.com/bible/1/MAT.9.13.KJV",
    verseText: "Go and learn what this means: ‘I desire mercy, and not sacrifice.’ For I came not to call the righteous, but sinners.”",
  },
  { 
    reference: "Psalm 92:12",
    referenceURL: "https://www.bible.com/bible/1/PSA.92.12.KJV",
    verseText: "The righteous flourish like the palm tree and grow like a cedar in Lebanon.",
  },
  { 
    reference: "Matthew 5:39",
    referenceURL: "https://www.bible.com/bible/1/MAT.5.39.KJV",
    verseText: "But I say to you, Do not resist the one who is evil. But if anyone slaps you on the right cheek, turn to him the other also.",
  },
  { 
    reference: "Proverbs 12:22",
    referenceURL: "https://www.bible.com/bible/1/PRO.12.22.KJV",
    verseText: "Lying lips are an abomination to the LORD, but those who act faithfully are his delight.",
  },
  { 
    reference: "1 Corinthians 1:25",
    referenceURL: "https://www.bible.com/bible/1/1CO.1.25.KJV",
    verseText: "For the foolishness of God is wiser than men, and the weakness of God is stronger than men.",
  },
  { 
    reference: "Esther 2:17",
    referenceURL: "https://www.bible.com/bible/1/EST.2.17.KJV",
    verseText: "the king loved Esther more than all the women, and she won grace and favor in his sight more than all the virgins, so that he set the royal crown on her head and made her queen instead of Vashti.",
  },
  { 
    reference: "1 Corinthians 13:12",
    referenceURL: "https://www.bible.com/bible/1/1CO.13.12.KJV",
    verseText: "For now we see in a mirror dimly, but then face to face. Now I know in part; then I shall know fully, even as I have been fully known.",
  },
  { 
    reference: "Luke 5:11",
    referenceURL: "https://www.bible.com/bible/1/LUK.5.11.KJV",
    verseText: "And when they had brought their boats to land, they left everything and followed him.",
  },
  { 
    reference: "Ephesians 6:11",
    referenceURL: "https://www.bible.com/bible/1/EPH.6.11.KJV",
    verseText: "Put on the whole armor of God, that you may be able to stand against the schemes of the devil.",
  },
  { 
    reference: "Proverbs 1:7",
    referenceURL: "https://www.bible.com/bible/1/PRO.1.7.KJV",
    verseText: "The fear of the LORD is the beginning of knowledge; fools despise wisdom and instruction.",
  },
  { 
    reference: "Psalm 112:5",
    referenceURL: "https://www.bible.com/bible/1/PSA.112.5.KJV",
    verseText: "It is well with the man who deals generously and lends; who conducts his affairs with justice.",
  },
  { 
    reference: "Ephesians 4:26",
    referenceURL: "https://www.bible.com/bible/1/EPH.4.26.KJV",
    verseText: "Be angry and do not sin; do not let the sun go down on your anger,",
  },
  { 
    reference: "Proverbs 27:23",
    referenceURL: "https://www.bible.com/bible/1/PRO.27.23.KJV",
    verseText: "Know well the condition of your flocks, and give attention to your herds,",
  },
  { 
    reference: "Genesis 32:28",
    referenceURL: "https://www.bible.com/bible/1/GEN.32.28.KJV",
    verseText: "Then he said, “Your name shall no longer be called Jacob, but Israel, for you have striven with God and with men, and have prevailed.”",
  },
  { 
    reference: "Proverbs 19:11",
    referenceURL: "https://www.bible.com/bible/1/PRO.19.11.KJV",
    verseText: "Good sense makes one slow to anger, and it is his glory to overlook an offense.",
  },
  { 
    reference: "Isaiah 40:8",
    referenceURL: "https://www.bible.com/bible/1/ISA.40.8.KJV",
    verseText: "The grass withereth, the flower fadeth: but the word of our God shall stand for ever."
  },
  { 
    reference: "Colossians 3:1",
    referenceURL: "https://www.bible.com/bible/1/COL.3.1.KJV",
    verseText: "If then you have been raised with Christ, seek the things that are above, where Christ is, seated at the right hand of God.",
  },
  { 
    reference: "Genesis 9:11",
    referenceURL: "https://www.bible.com/bible/1/GEN.9.11.KJV",
    verseText: "I establish my covenant with you, that never again shall all flesh be cut off by the waters of the flood, and never again shall there be a flood to destroy the earth.”",
  },
  { 
    reference: "Isaiah 53:9",
    referenceURL: "https://www.bible.com/bible/1/ISA.53.9.KJV",
    verseText: "And they made his grave with the wicked and with a rich man in his death, although he had done no violence, and there was no deceit in his mouth.",
  },
  { 
    reference: "Joshua 4:23",
    referenceURL: "https://www.bible.com/bible/1/JOS.4.23.KJV",
    verseText: "For the LORD your God dried up the waters of the Jordan for you until you passed over, as the LORD your God did to the Red Sea, which he dried up for us until we passed over,",
  },
  { 
    reference: "1 Corinthians 1:18",
    referenceURL: "https://www.bible.com/bible/1/1CO.1.18.KJV",
    verseText: "For the preaching of the cross is to them that perish foolishness; but unto us which are saved it is the power of God."
  },
  { 
    reference: "James 1:27",
    referenceURL: "https://www.bible.com/bible/1/JAS.1.27.KJV",
    verseText: "Religion that is pure and undefiled before God the Father is this: to visit orphans and widows in their affliction, and to keep oneself unstained from the world.",
  },
  { 
    reference: "Hebrews 2:9",
    referenceURL: "https://www.bible.com/bible/1/HEB.2.9.KJV",
    verseText: "But we see him who for a little while was made lower than the angels, namely Jesus, crowned with glory and honor because of the suffering of death, so that by the grace of God he might taste death for everyone.",
  },
  { 
    reference: "Matthew 18:15",
    referenceURL: "https://www.bible.com/bible/1/MAT.18.15.KJV",
    verseText: "“If your brother sins against you, go and tell him his fault, between you and him alone. If he listens to you, you have gained your brother.",
  },
  { 
    reference: "Matthew 7:11",
    referenceURL: "https://www.bible.com/bible/1/MAT.7.11.KJV",
    verseText: "If you then, who are evil, know how to give good gifts to your children, how much more will your Father who is in heaven give good things to those who ask him!",
  },
  { 
    reference: "Exodus 12:39",
    referenceURL: "https://www.bible.com/bible/1/EXO.12.39.KJV",
    verseText: "And they baked unleavened cakes of the dough that they had brought out of Egypt, for it was not leavened, because they were thrust out of Egypt and could not wait, nor had they prepared any provisions for themselves.",
  },
  { 
    reference: "1 Timothy 6:10",
    referenceURL: "https://www.bible.com/bible/1/1TI.6.10.KJV",
    verseText: "For the love of money is a root of all kinds of evils. It is through this craving that some have wandered away from the faith and pierced themselves with many pangs.",
  },
  { 
    reference: "Psalm 36:7",
    referenceURL: "https://www.bible.com/bible/1/PSA.36.7.KJV",
    verseText: "How precious is your steadfast love, O God! The children of mankind take refuge in the shadow of your wings.",
  },
  { 
    reference: "2 Corinthians 13:12",
    referenceURL: "https://www.bible.com/bible/1/2CO.13.12.KJV",
    verseText: "Greet one another with a holy kiss.",
  },
  { 
    reference: "John 5:18",
    referenceURL: "https://www.bible.com/bible/1/JHN.5.18.KJV",
    verseText: "This was why the Jews were seeking all the more to kill him, because not only was he breaking the Sabbath, but he was even calling God his own Father, making himself equal with God.",
  },
  { 
    reference: "Psalm 17:15",
    referenceURL: "https://www.bible.com/bible/1/PSA.17.15.KJV",
    verseText: "As for me, I shall behold your face in righteousness; when I awake, I shall be satisfied with your likeness.",
  },
  { 
    reference: "Romans 12:9",
    referenceURL: "https://www.bible.com/bible/1/ROM.12.9.KJV",
    verseText: "Let love be genuine. Abhor what is evil; hold fast to what is good.",
  },
  { 
    reference: "Job 1:22",
    referenceURL: "https://www.bible.com/bible/1/JOB.1.22.KJV",
    verseText: "In all this Job did not sin or charge God with wrong.",
  },
  { 
    reference: "Psalm 133:1",
    referenceURL: "https://www.bible.com/bible/1/PSA.133.1.KJV",
    verseText: "A Song of Ascents. Of David. Behold, how good and pleasant it is when brothers dwell in unity!",
  },
  { 
    reference: "James 1:2",
    referenceURL: "https://www.bible.com/bible/1/JAS.1.2.KJV",
    verseText: "Count it all joy, my brothers, when you meet trials of various kinds,",
  },
  { 
    reference: "Proverbs 1:14",
    referenceURL: "https://www.bible.com/bible/1/PRO.1.14.KJV",
    verseText: "throw in your lot among us; we will all have one purse”—",
  },
  { 
    reference: "Psalm 46:7",
    referenceURL: "https://www.bible.com/bible/1/PSA.46.7.KJV",
    verseText: "The LORD of hosts is with us; the God of Jacob is our fortress. Selah",
  },
  { 
    reference: "2 Corinthians 6:14",
    referenceURL: "https://www.bible.com/bible/1/2CO.6.14.KJV",
    verseText: "Do not be unequally yoked with unbelievers. For what partnership has righteousness with lawlessness? Or what fellowship has light with darkness?",
  },
  { 
    reference: "Luke 12:35",
    referenceURL: "https://www.bible.com/bible/1/LUK.12.35.KJV",
    verseText: "“Stay dressed for action and keep your lamps burning,",
  },
  { 
    reference: "John 1:14",
    referenceURL: "https://www.bible.com/bible/1/JHN.1.14.KJV",
    verseText: "And the Word was made flesh, and dwelt among us, (and we beheld his glory, the glory as of the only begotten of the Father,) full of grace and truth."
  },
  { 
    reference: "Jude 1:4",
    referenceURL: "https://www.bible.com/bible/1/JDG.1.4.KJV",
    verseText: "For certain people have crept in unnoticed who long ago were designated for this condemnation, ungodly people, who pervert the grace of our God into sensuality and deny our only Master and Lord, Jesus Christ.",
  },
  { 
    reference: "Genesis 30:13",
    referenceURL: "https://www.bible.com/bible/1/GEN.30.13.KJV",
    verseText: "And Leah said, “Happy am I! For women have called me happy.” So she called his name Asher.",
  },
  { 
    reference: "Psalm 145:3",
    referenceURL: "https://www.bible.com/bible/1/PSA.145.3.KJV",
    verseText: "Great is the LORD, and greatly to be praised, and his greatness is unsearchable.",
  },
  { 
    reference: "Matthew 3:4",
    referenceURL: "https://www.bible.com/bible/1/MAT.3.4.KJV",
    verseText: "Now John wore a garment of camel’s hair and a leather belt around his waist, and his food was locusts and wild honey.",
  },
  { 
    reference: "Judges 15:15",
    referenceURL: "https://www.bible.com/bible/1/JDG.15.15.KJV",
    verseText: "And he found a fresh jawbone of a donkey, and put out his hand and took it, and with it he struck 1,000 men.",
  },
  { 
    reference: "Proverbs 31:30",
    referenceURL: "https://www.bible.com/bible/1/PRO.31.30.KJV",
    verseText: "Charm is deceitful, and beauty is vain, but a woman who fears the LORD is to be praised.",
  },
  { 
    reference: "Romans 6:23",
    referenceURL: "https://www.bible.com/bible/1/ROM.6.23.KJV",
    verseText: "For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord.",
  },
  { 
    reference: "Genesis 17:19",
    referenceURL: "https://www.bible.com/bible/1/GEN.17.19.KJV",
    verseText: "God said, “No, but Sarah your wife shall bear you a son, and you shall call his name Isaac. I will establish my covenant with him as an everlasting covenant for his offspring after him.",
  },
  { 
    reference: "Jeremiah 2:13",
    referenceURL: "https://www.bible.com/bible/1/JER.2.13.KJV",
    verseText: "for my people have committed two evils: they have forsaken me, the fountain of living waters, and hewed out cisterns for themselves, broken cisterns that can hold no water.",
  },
  { 
    reference: "Job 41:18",
    referenceURL: "https://www.bible.com/bible/1/JOB.41.18.KJV",
    verseText: "His sneezings flash forth light, and his eyes are like the eyelids of the dawn.",
  },
  {  
    reference: "Luke 10:3",
    referenceURL: "https://www.bible.com/bible/1/LUK.10.3.KJV",
    verseText: "Go your way; behold, I am sending you out as lambs in the midst of wolves.",
  },
  {  
    reference: "Mark 16:4",
    referenceURL: "https://www.bible.com/bible/1/MRK.16.4.KJV",
    verseText: "And looking up, they saw that the stone had been rolled back—it was very large.",
  },
  {  
    reference: "Luke 8:24",
    referenceURL: "https://www.bible.com/bible/1/LUK.8.24.KJV",
    verseText: "And they went and woke him, saying, “Master, Master, we are perishing!” And he awoke and rebuked the wind and the raging waves, and they ceased, and there was a calm.",
  },
  {  
    reference: "John 6:15",
    referenceURL: "https://www.bible.com/bible/1/JHN.6.15.KJV",
    verseText: "Perceiving then that they were about to come and take him by force to make him king, Jesus withdrew again to the mountain by himself.",
  },
  {  
    reference: "Proverbs 25:11",
    referenceURL: "https://www.bible.com/bible/1/PRO.25.11.KJV",
    verseText: "A word fitly spoken Is like apples of gold in pictures of silver."
  },
  {  
    reference: "Mark 5:41",
    referenceURL: "https://www.bible.com/bible/1/MRK.4.41.KJV",
    verseText: "Taking her by the hand he said to her, “Talitha cumi,” which means, “Little girl, I say to you, arise.”",
  },
  {  
    reference: "Proverbs 5:22",
    referenceURL: "https://www.bible.com/bible/1/PRO.5.22.KJV",
    verseText: "The iniquities of the wicked ensnare him, and he is held fast in the cords of his sin.",
  },
  {  
    reference: "Psalm 89:34",
    referenceURL: "https://www.bible.com/bible/1/PSA.89.34.KJV",
    verseText: "My covenant will I not break, nor alter the thing that is gone out of my lips."
  },
  {  
    reference: "Psalm 34:4",
    referenceURL: "https://www.bible.com/bible/1/PSA.34.4.KJV",
    verseText: "I sought the LORD, and he answered me and delivered me from all my fears.",
  },
  {  
    reference: "Proverbs 15:17",
    referenceURL: "https://www.bible.com/bible/1/PRO.15.17.KJV",
    verseText: "Better is a dinner of herbs where love is than a fattened ox and hatred with it.",
  },
  {  
    reference: "Hebrews 10:14",
    referenceURL: "https://www.bible.com/bible/1/HEB.10.14.KJV",
    verseText: "For by a single offering he has perfected for all time those who are being sanctified.",
  },
  {  
    reference: "Jonah 1:17",
    referenceURL: "https://www.bible.com/bible/1/JON.1.17.KJV",
    verseText: "And the LORD appointed a great fish to swallow up Jonah. And Jonah was in the belly of the fish three days and three nights.",
  },
  {  
    reference: "Ruth 2:2",
    referenceURL: "https://www.bible.com/bible/1/RUT.2.2.KJV",
    verseText: "And Ruth the Moabite said to Naomi, “Let me go to the field and glean among the ears of grain after him in whose sight I shall find favor.” And she said to her, “Go, my daughter.”",
  },
  {  
    reference: "Judges 15:4",
    referenceURL: "https://www.bible.com/bible/1/JDG.15.4.KJV",
    verseText: "So Samson went and caught 300 foxes and took torches. And he turned them tail to tail and put a torch between each pair of tails.",
  },
  {  
    reference: "Revelation 21:18",
    referenceURL: "https://www.bible.com/bible/1/REV.21.18.KJV",
    verseText: "The wall was built of jasper, while the city was pure gold, like clear glass.",
  },
  {  
    reference: "Proverbs 20:15",
    referenceURL: "https://www.bible.com/bible/1/PRO.20.15.KJV",
    verseText: "There is gold and abundance of costly stones, but the lips of knowledge are a precious jewel.",
  },
  {  
    reference: "Psalm 121:1-2",
    referenceURL: "https://www.bible.com/bible/1/PSA.121.1-2.KJV",
    verseText: "I lift up my eyes to the hills. From where does my help come? My help comes from the LORD, who made heaven and earth.",
  },
  {  
    reference: "Colossians 3:16",
    referenceURL: "https://www.bible.com/bible/1/COL.3.16.KJV",
    verseText: "Let the word of Christ dwell in you richly in all wisdom; teaching and admonishing one another in psalms and hymns and spiritual songs, singing with grace in your hearts to the Lord."
  },
  {  
    reference: "John 12:3",
    referenceURL: "https://www.bible.com/bible/1/JHN.12.3.KJV",
    verseText: "Mary therefore took a pound of expensive ointment made from pure nard, and anointed the feet of Jesus and wiped his feet with her hair. The house was filled with the fragrance of the perfume.",
  },
  {  
    reference: "Numbers 13:30",
    referenceURL: "https://www.bible.com/bible/1/NUM.13.30.KJV",
    verseText: "But Caleb quieted the people before Moses and said, “Let us go up at once and occupy it, for we are well able to overcome it.”",
  },
  {  
    reference: "Psalm 16:2",
    referenceURL: "https://www.bible.com/bible/1/PSA.16.2.KJV",
    verseText: "I say to the LORD, “You are my Lord; I have no good apart from you.”",
  },
  {  
    reference: "Ephesians 1:4",
    referenceURL: "https://www.bible.com/bible/1/EPH.1.4.KJV",
    verseText: "even as he chose us in him before the foundation of the world, that we should be holy and blameless before him. In love",
  },
  {  
    reference: "Luke 3:7",
    referenceURL: "https://www.bible.com/bible/1/LUK.3.7.KJV",
    verseText: "He said therefore to the crowds that came out to be baptized by him, “You brood of vipers! Who warned you to flee from the wrath to come?",
  },
  {  
    reference: "Psalm 89:9",
    referenceURL: "https://www.bible.com/bible/1/PSA.89.9.KJV",
    verseText: "You rule the raging of the sea; when its waves rise, you still them.",
  },
  {  
    reference: "Hebrews 11:1",
    referenceURL: "https://www.bible.com/bible/1/HEB.11.1.KJV",
    verseText: "Now faith is the assurance of things hoped for, the conviction of things not seen.",
  },
  {  
    reference: "John 12:6",
    referenceURL: "https://www.bible.com/bible/1/JHN.12.6.KJV",
    verseText: "He said this, not because he cared about the poor, but because he was a thief, and having charge of the moneybag he used to help himself to what was put into it.",
  },
  {  
    reference: "Luke 15:17",
    referenceURL: "https://www.bible.com/bible/1/LUK.15.17.KJV",
    verseText: "“But when he came to himself, he said, ‘How many of my father’s hired servants have more than enough bread, but I perish here with hunger!",
  },
  {  
    reference: "Exodus 33:22",
    referenceURL: "https://www.bible.com/bible/1/EXO.33.22.KJV",
    verseText: "and while my glory passes by I will put you in a cleft of the rock, and I will cover you with my hand until I have passed by.",
  },
  {  
    reference: "Ecclesiastes 2:14",
    referenceURL: "https://www.bible.com/bible/1/ECC.2.14.KJV",
    verseText: "The wise person has his eyes in his head, but the fool walks in darkness. And yet I perceived that the same event happens to all of them.",
  },
  {  
    reference: "Genesis 4:21",
    referenceURL: "https://www.bible.com/bible/1/GEN.4.21.KJV",
    verseText: "His brother’s name was Jubal; he was the father of all those who play the lyre and pipe.",
  },
  {  
    reference: "Exodus 3:2",
    referenceURL: "https://www.bible.com/bible/1/EXO.3.2.KJV",
    verseText: "And the angel of the LORD appeared to him in a flame of fire out of the midst of a bush. He looked, and behold, the bush was burning, yet it was not consumed.",
  }
];